[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpufit-wgpu"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "webgpu>=1.1.0",
    "numpy>=1.24",
]

[project.optional-dependencies]
plot = ["matplotlib>=3.10.8"]
demo = ["brimfile[remote-store]", "matplotlib>=3.10.8"]

[tool.hatch.build.targets.wheel]
packages = ["gpufit_wgpu"]
